version: "3.7"

services:
  shape-visualizer_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - "/app/node_modules"
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CHOKIDAR_USEPOLLING=true
