version: "3.7"

services:
  shape-visualizer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - "/app/node_modules"
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - CHOKIDAR_USEPOLLING=true
