version: "3.7"

services:
  shape-visualizer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - "/app/node_modules"
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - CHOKIDAR_USEPOLLING=true
  tests:
    image: "cypress/included:6.4.0"
    depends_on:
      - shape-visualizer
    environment:
      - CYPRESS_baseUrl=http://shape-visualizer:8000
    working_dir: /tests
    volumes:
      - ./:/tests
