# from base image
FROM node:alpine

# set workdir
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./

RUN npm install 

RUN npm install -g react-scripts

COPY . ./

CMD [ "npm","start" ]
